INCLUDE(FindPackageHandleStandardArgs)

IF (NOT DEFINED AGILE_ROOT_DIR)
  IF (EXISTS /usr/local/include/agile)
    SET(AGILE_ROOT_DIR /usr/local/)
  ELSE ()
    MESSAGE(FATAL_ERROR "AGILE_ROOT_DIR not defined.  ")
  ENDIF()
ENDIF()

SET(AGILE_IncludeSearchPaths ${AGILE_ROOT_DIR}/CUDA/inc ${AGILE_ROOT_DIR}/include/agile /usr/local/include)
SET(AGILE_LibrarySearchPaths ${AGILE_ROOT_DIR}/CUDA/bin ${AGILE_ROOT_DIR}/lib /usr/local/lib)

FIND_PATH(AGILE_INCLUDE_DIRS NAMES agile.hpp PATHS ${AGILE_IncludeSearchPaths})

FIND_LIBRARY(AGILE_LIBRARIES NAMES agile PATHS ${AGILE_LibrarySearchPaths})

#Handle the REQUIRED argument and set the < UPPERCASED_NAME > _FOUND variable
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AGILE "Could NOT find AGILE." AGILE_LIBRARIES AGILE_INCLUDE_DIRS)
IF(AGILE_FOUND)
  FIND_PACKAGE_MESSAGE(
      AGILE      
      "Found AGILE ${AGILE_LIBRARIES} ${AGILE_INCLUDE_DIRS}"
      "[${AGILE_LIBRARIES}][${AGILE_INCLUDE_DIRS}]")
  ENDIF(AGILE_FOUND)
MARK_AS_ADVANCED(AGILE_INCLUDE_DIRS AGILE_LIBRARIES)
